load:
  - ./modules/deepstream-server
  - ./modules/udp-advertisement
  - ./modules/web-server
modules:
  - component: deepstream-server
    config:
      port: 6020
  - component: udp-advertisement
    config:
      requestPort: 6031
  - component: web-server
    config:
      port: 6080
      host: localhost
      apps:
        iw-introspection: node_modules/iw-introspection